import {
  Activity,
  BadgeCheck,
  BarChart3,
  Boxes,
  ClipboardCheck,
  CreditCard,
  FileCheck2,
  LayoutDashboard,
  PackageCheck,
  PackagePlus,
  ShieldCheck,
  ShoppingCart,
  Truck,
  Users,
  Warehouse,
} from 'lucide-react'
import type { Alert, ForecastPoint, InventoryItem, Order, Role, Vendor, WorkflowStep } from './types'

export const roles: Role[] = ['Command Center', 'Hospital', 'Vendor', 'Distributor']

export const inventory: InventoryItem[] = [
  {
    id: 'MED-PCM-500',
    name: 'Paracetamol 500mg',
    genericName: 'Acetaminophen',
    category: 'Essential',
    batch: 'PCM24A91',
    vendor: 'Aarogya Pharma',
    manufacturer: 'Aarogya Formulations',
    warehouse: 'North Hub',
    state: 'Delhi NCR',
    quantity: 18340,
    reserved: 2800,
    reorderPoint: 12000,
    safetyStock: 5400,
    forecast30d: 16800,
    leadTimeDays: 4,
    unitCost: 0.92,
    mrp: 1.45,
    expiry: '2027-04-12',
    temperatureBand: 'Ambient',
    temperatureNow: 24,
    complianceScore: 98,
    status: 'Healthy',
    consumption: [11900, 12780, 13220, 14110, 15300, 16800],
  },
  {
    id: 'MED-INS-RAP',
    name: 'Rapid Insulin 100IU',
    genericName: 'Insulin Lispro',
    category: 'Cold Chain',
    batch: 'INS24L07',
    vendor: 'BioSure Lifesciences',
    manufacturer: 'BioSure Biologics',
    warehouse: 'West Cold Store',
    state: 'Maharashtra',
    quantity: 2180,
    reserved: 760,
    reorderPoint: 3000,
    safetyStock: 1200,
    forecast30d: 3920,
    leadTimeDays: 8,
    unitCost: 218,
    mrp: 296,
    expiry: '2026-11-21',
    temperatureBand: '2-8C',
    temperatureNow: 6,
    complianceScore: 94,
    status: 'Reorder',
    consumption: [2610, 2740, 2960, 3150, 3440, 3920],
  },
  {
    id: 'MED-CEF-1G',
    name: 'Ceftriaxone Injection 1g',
    genericName: 'Ceftriaxone Sodium',
    category: 'Antibiotic',
    batch: 'CEF24Q22',
    vendor: 'JanAushadhi Supply Co.',
    manufacturer: 'SterileCare Labs',
    warehouse: 'East Regional Hub',
    state: 'West Bengal',
    quantity: 4620,
    reserved: 1180,
    reorderPoint: 6500,
    safetyStock: 2300,
    forecast30d: 7200,
    leadTimeDays: 6,
    unitCost: 31,
    mrp: 45,
    expiry: '2027-02-02',
    temperatureBand: 'Ambient',
    temperatureNow: 25,
    complianceScore: 92,
    status: 'Critical',
    consumption: [4510, 4880, 5020, 5740, 6410, 7200],
  },
  {
    id: 'MED-ORS-21',
    name: 'ORS Sachet WHO',
    genericName: 'Oral Rehydration Salts',
    category: 'Emergency',
    batch: 'ORS24M10',
    vendor: 'HealthGrid Meds',
    manufacturer: 'HydraLife Remedies',
    warehouse: 'South Hub',
    state: 'Karnataka',
    quantity: 51200,
    reserved: 9000,
    reorderPoint: 28000,
    safetyStock: 11000,
    forecast30d: 43800,
    leadTimeDays: 3,
    unitCost: 2.4,
    mrp: 4.0,
    expiry: '2026-10-04',
    temperatureBand: 'Ambient',
    temperatureNow: 26,
    complianceScore: 89,
    status: 'Expiry Watch',
    consumption: [26400, 29100, 31800, 37400, 41600, 43800],
  },
  {
    id: 'MED-AMO-625',
    name: 'Amoxiclav 625mg',
    genericName: 'Amoxicillin + Clavulanate',
    category: 'Antibiotic',
    batch: 'AMX24B44',
    vendor: 'JanAushadhi Supply Co.',
    manufacturer: 'SterileCare Labs',
    warehouse: 'North Hub',
    state: 'Uttar Pradesh',
    quantity: 6840,
    reserved: 1540,
    reorderPoint: 7000,
    safetyStock: 2500,
    forecast30d: 8300,
    leadTimeDays: 5,
    unitCost: 18.5,
    mrp: 26,
    expiry: '2027-01-18',
    temperatureBand: 'Ambient',
    temperatureNow: 25,
    complianceScore: 96,
    status: 'Reorder',
    consumption: [5980, 6120, 6600, 7040, 7870, 8300],
  },
  {
    id: 'MED-BCG-VAC',
    name: 'BCG Vaccine 10 Dose',
    genericName: 'Bacillus Calmette-Guerin',
    category: 'Vaccine',
    batch: 'BCG24C12',
    vendor: 'BioSure Lifesciences',
    manufacturer: 'BioSure Biologics',
    warehouse: 'Central Immunization Vault',
    state: 'Telangana',
    quantity: 920,
    reserved: 400,
    reorderPoint: 1400,
    safetyStock: 600,
    forecast30d: 1510,
    leadTimeDays: 10,
    unitCost: 76,
    mrp: 92,
    expiry: '2026-12-14',
    temperatureBand: '2-8C',
    temperatureNow: 9,
    complianceScore: 81,
    status: 'Cold Chain Alert',
    consumption: [910, 950, 1040, 1220, 1310, 1510],
  },
  {
    id: 'MED-MET-500',
    name: 'Metformin 500mg',
    genericName: 'Metformin Hydrochloride',
    category: 'Chronic',
    batch: 'MET24S31',
    vendor: 'Aarogya Pharma',
    manufacturer: 'Aarogya Formulations',
    warehouse: 'West Hub',
    state: 'Gujarat',
    quantity: 23600,
    reserved: 3600,
    reorderPoint: 15000,
    safetyStock: 5200,
    forecast30d: 19800,
    leadTimeDays: 4,
    unitCost: 0.78,
    mrp: 1.25,
    expiry: '2027-08-19',
    temperatureBand: 'Ambient',
    temperatureNow: 24,
    complianceScore: 99,
    status: 'Healthy',
    consumption: [17400, 17920, 18300, 18900, 19210, 19800],
  },
  {
    id: 'MED-OXY-10',
    name: 'Oxygen Concentrator Filter Kit',
    genericName: 'Medical Device Consumable',
    category: 'Device Consumable',
    batch: 'OXY24F18',
    vendor: 'HealthGrid Meds',
    manufacturer: 'CarePulse Devices',
    warehouse: 'South Hub',
    state: 'Tamil Nadu',
    quantity: 1380,
    reserved: 220,
    reorderPoint: 900,
    safetyStock: 300,
    forecast30d: 780,
    leadTimeDays: 7,
    unitCost: 420,
    mrp: 540,
    expiry: '2028-01-01',
    temperatureBand: 'Ambient',
    temperatureNow: 25,
    complianceScore: 95,
    status: 'Healthy',
    consumption: [640, 690, 720, 760, 790, 780],
  },
]

export const orders: Order[] = [
  {
    id: 'PO-2026-0829-041',
    buyer: 'AIIMS Trauma Centre',
    seller: 'JanAushadhi Supply Co.',
    drug: 'Ceftriaxone Injection 1g',
    quantity: 3200,
    value: 99200,
    status: 'In Transit',
    eta: '2026-08-31',
    source: 'East Regional Hub',
    destination: 'Delhi NCR',
    temperatureBand: 'Ambient',
    risk: 'Medium',
    timeline: [
      { label: 'Order received', at: '2026-08-28 09:40', done: true },
      { label: 'License and stock verified', at: '2026-08-28 10:15', done: true },
      { label: 'Dispatched', at: '2026-08-28 18:05', done: true },
      { label: 'In transit', at: '2026-08-29 08:30', done: true },
      { label: 'Quality check', at: 'Expected 2026-08-31', done: false },
      { label: 'Delivered', at: 'Expected 2026-08-31', done: false },
    ],
  },
  {
    id: 'PO-2026-0829-042',
    buyer: 'District Hospital Pune',
    seller: 'BioSure Lifesciences',
    drug: 'Rapid Insulin 100IU',
    quantity: 840,
    value: 183120,
    status: 'Quality Check',
    eta: '2026-08-29',
    source: 'West Cold Store',
    destination: 'Maharashtra',
    temperatureBand: '2-8C',
    risk: 'Low',
    timeline: [
      { label: 'Order received', at: '2026-08-27 13:20', done: true },
      { label: 'Cold-chain slot booked', at: '2026-08-27 14:00', done: true },
      { label: 'Dispatched', at: '2026-08-28 06:45', done: true },
      { label: 'In transit', at: '2026-08-28 16:15', done: true },
      { label: 'Quality check', at: '2026-08-29 10:10', done: true },
      { label: 'Delivered', at: 'Expected 2026-08-29', done: false },
    ],
  },
  {
    id: 'PO-2026-0828-037',
    buyer: 'Karnataka Medical Services Corp.',
    seller: 'HealthGrid Meds',
    drug: 'ORS Sachet WHO',
    quantity: 18000,
    value: 43200,
    status: 'Delivered',
    eta: '2026-08-28',
    source: 'South Hub',
    destination: 'Karnataka',
    temperatureBand: 'Ambient',
    risk: 'Low',
    timeline: [
      { label: 'Order received', at: '2026-08-26 12:25', done: true },
      { label: 'Stock reserved', at: '2026-08-26 13:15', done: true },
      { label: 'Dispatched', at: '2026-08-27 07:45', done: true },
      { label: 'In transit', at: '2026-08-27 14:45', done: true },
      { label: 'Quality check', at: '2026-08-28 08:50', done: true },
      { label: 'Delivered', at: '2026-08-28 11:30', done: true },
    ],
  },
]

export const vendors: Vendor[] = [
  {
    id: 'VEN-AAR',
    name: 'Aarogya Pharma',
    license: 'DL-20B-2026-1041',
    state: 'Gujarat',
    reliability: 97,
    fillRate: 96,
    avgLeadTime: 4,
    qualityScore: 98,
    activeBatches: 42,
  },
  {
    id: 'VEN-BIO',
    name: 'BioSure Lifesciences',
    license: 'DL-21G-2026-2217',
    state: 'Maharashtra',
    reliability: 92,
    fillRate: 90,
    avgLeadTime: 8,
    qualityScore: 94,
    activeBatches: 18,
  },
  {
    id: 'VEN-JAN',
    name: 'JanAushadhi Supply Co.',
    license: 'DL-20B-2026-3108',
    state: 'West Bengal',
    reliability: 89,
    fillRate: 87,
    avgLeadTime: 6,
    qualityScore: 92,
    activeBatches: 31,
  },
  {
    id: 'VEN-HGM',
    name: 'HealthGrid Meds',
    license: 'DL-20-2026-7712',
    state: 'Karnataka',
    reliability: 94,
    fillRate: 93,
    avgLeadTime: 3,
    qualityScore: 91,
    activeBatches: 26,
  },
]

export const alerts: Alert[] = [
  {
    id: 'ALT-101',
    title: 'BCG cold-chain deviation',
    detail: 'Central Immunization Vault recorded 9C for 22 minutes. Quarantine batch BCG24C12 until QA release.',
    severity: 'Critical',
    owner: 'Vendor',
    createdAt: '2026-08-29 10:26',
  },
  {
    id: 'ALT-102',
    title: 'Ceftriaxone runout risk',
    detail: 'Projected stockout in 19 days for North Hub demand unless 4,880 units are replenished.',
    severity: 'Warning',
    owner: 'Distributor',
    createdAt: '2026-08-29 09:50',
  },
  {
    id: 'ALT-103',
    title: 'ORS expiry redistribution',
    detail: '10,600 sachets should be moved to high-consumption districts before 2026-09-14.',
    severity: 'Warning',
    owner: 'Command Center',
    createdAt: '2026-08-29 09:10',
  },
  {
    id: 'ALT-104',
    title: 'License verification passed',
    detail: 'Aarogya Pharma and HealthGrid Meds renewed distributor-facing compliance documents.',
    severity: 'Info',
    owner: 'Hospital',
    createdAt: '2026-08-29 08:35',
  },
]

export const forecast: ForecastPoint[] = [
  { month: 'Mar', essential: 40200, chronic: 24100, emergency: 14800, predictedDemand: 78200, actualDemand: 76100 },
  { month: 'Apr', essential: 42600, chronic: 25300, emergency: 16200, predictedDemand: 82100, actualDemand: 81300 },
  { month: 'May', essential: 44800, chronic: 26600, emergency: 18100, predictedDemand: 87500, actualDemand: 86800 },
  { month: 'Jun', essential: 49200, chronic: 27100, emergency: 22400, predictedDemand: 95700, actualDemand: 98200 },
  { month: 'Jul', essential: 53600, chronic: 28400, emergency: 25100, predictedDemand: 105500, actualDemand: 104900 },
  { month: 'Aug', essential: 58400, chronic: 30300, emergency: 28900, predictedDemand: 116100, actualDemand: 113700 },
  { month: 'Sep', essential: 61200, chronic: 31800, emergency: 30700, predictedDemand: 123700, actualDemand: 0 },
]

export const workflow: WorkflowStep[] = [
  {
    title: 'License Verification',
    description: 'Vendor and distributor onboarding checks drug license, GSTIN, storage certificate, and QA contact.',
    icon: FileCheck2,
  },
  {
    title: 'Available Stock',
    description: 'Batch-level inventory tracks reserved units, location, expiry, temperature band, and real-time status.',
    icon: Boxes,
  },
  {
    title: 'Procurement Cart',
    description: 'Hospitals compare stock, lead time, price, and compliance before raising a purchase order.',
    icon: ShoppingCart,
  },
  {
    title: 'Dispatch and Tracking',
    description: 'Distributor confirms pick-pack-dispatch events with route, ETA, and cold-chain telemetry.',
    icon: Truck,
  },
  {
    title: 'Quality and Billing',
    description: 'Receiving teams complete QA, update stock, and generate invoice records against delivered orders.',
    icon: CreditCard,
  },
  {
    title: 'AI Forecasting',
    description: 'Forecast engine detects demand surges, projected stockout, and redistribution opportunities.',
    icon: BarChart3,
  },
]

export const moduleTiles = [
  { title: 'Dashboard', icon: LayoutDashboard, owner: 'All roles', detail: 'Live KPIs, alerts, and supply chain health.' },
  { title: 'Inventory', icon: Warehouse, owner: 'Vendor + Distributor', detail: 'Batch stock, expiry, reserved quantity, and reorder logic.' },
  { title: 'Store', icon: PackagePlus, owner: 'Hospital', detail: 'Validated procurement cart with price and lead-time comparison.' },
  { title: 'Orders', icon: PackageCheck, owner: 'All roles', detail: 'PO lifecycle, dispatch, order received, and delivery proof.' },
  { title: 'Compliance', icon: ShieldCheck, owner: 'Admin + QA', detail: 'License, cold chain, batch traceability, and audit controls.' },
  { title: 'Users', icon: Users, owner: 'Admin', detail: 'Role-based onboarding and approval workflows.' },
  { title: 'Monitoring', icon: Activity, owner: 'Command Center', detail: 'Demand spikes, stockouts, wastage, and SLA monitoring.' },
  { title: 'QA Sign-off', icon: ClipboardCheck, owner: 'Hospital + Distributor', detail: 'Condition, expiry, invoice, and proof of receipt.' },
  { title: 'Verified Network', icon: BadgeCheck, owner: 'Government', detail: 'Trusted supply partners with performance scoring.' },
]
